### ISSUE TITLE
[DShield.org-Suspicious-Domain-List] domain.list not updating

### ISSUE THREAD

**Issue by dnmTX** [Ultimate-Hosts-Blacklist/dev-center#10]
@funilrys  i've been keeping an eye on this one and so far,from my own observations the [original lists](https://www.dshield.org/feeds/suspiciousdomains_Low.txt) it's been regenerated every day and if you look at the bottom it shows how many domains are present:
![dshield](https://user-images.githubusercontent.com/34774426/46374443-56c46a00-c656-11e8-9397-df35d7c51cd7.png)

This number varies from day to day,aka domains are being added or removed
(2 days ago was like 18014)
Looking at the `domain.list` last update was 10 days ago: 
![dshield1](https://user-images.githubusercontent.com/34774426/46374657-da7e5680-c656-11e8-9c20-c7302f4343d3.png)
So why it doesn't updating,you said that if there is a update from upstream the `domain.list` will update itself right away? Excuse me if i misunderstood something,again,but i have to ask(could be a bug for what i know)

**Comment by funilrys** [comment]
Issue with Travis CI, our cross repository configuration and our infrastructure script.
Just published the fix and launched the infrastructure build restart procedure. 

All build are currently starting back. All tests are coming asap and as usual there can be some delay due to Travis CI limitation.

Closing.

**Comment by dnmTX** [comment]
@funilrys  thanks 👍
