### ISSUE TITLE
Support from hostsVN - advertising block of Vietnam

### ISSUE THREAD

**Issue by funilrys** [Ultimate-Hosts-Blacklist/dev-center#36]
@bigdargon [said](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/516)

> Hello!
> 
> I am from Vietnam, I have a project `hostsVN` for the purpose of blocking ads and tracking from advertisers from Vietnam. Wishing to support ad blocking projects that support blocking domains in Vietnam, so I created this issue hoping you will merge with hostsVN. The project has been maintained for more than 1 year and continuously updates new domain names.
> 
> Github: https://github.com/bigdargon/hostsVN/
> 
> Some sources use hostsVN:
> - https://abpvn.com/android/
> - https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/2437fd7f0b9586ef53a417dd63a59deac43452b0/Filters/filter.template#L92
> - in `nextdns` lists
> 
> I have a hosts file that supports all advertisers and followers that Vietnamese people regularly access. Link https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
> 
> And the hosts file I categorized only includes domain name blocking ads and tracking in Vietnam. I hope you just need to merge this file. Link https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hosts-VN
> 
> Thanks you!

**Comment by funilrys** [comment]
Test/Comparison result: https://github.com/Ultimate-Hosts-Blacklist/dev-center/pull/37#issuecomment-520268352

**Comment by bigdargon** [comment]
Hello!  Thank you for checking!  hostsVN includes many different options for Vietnamese people to choose to block ads!  I build the hosts-VN file that only includes the advertiser in Vietnam, and the hosts file is included with all the advertising domains in Vietnam frequently accessed!

I hope you can check this file https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hosts-VN and add it to the "basic" source, because currently the blocklist has not added advertising domain names in Vietnam!

and I created PR on Steven Black's host source https://github.com/StevenBlack/hosts/commit/e56bf74c53ff5c5053cd80836f9aaccb795f4725

**Comment by funilrys** [comment]
https://github.com/Ultimate-Hosts-Blacklist/hostsVN
